name       : zoitechat
version    : 2.18.0
release    : 1
source     :
    - https://github.com/ZoiteChat/zoitechat/archive/refs/tags/zoitechat-2.18.0-pre1.tar.gz : d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed
homepage   : https://zoitechat.zoite.net/
license    : GPL-2.0-only
component  : network.irc
summary    : HexChat-based IRC client
description: |
    ZoiteChat is a HexChat-based IRC client for Windows and UNIX-like systems.
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ayatana-appindicator3-0.1)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(libcanberra)
    - pkgconfig(openssl)
    - pkgconfig(iso-codes)
    - meson
    - ninja
    - pkgconfig
    - gcc
    - gettext
setup      : |
    %meson_configure \
        -Dgtk-frontend=true \
        -Dgtk3=true \
        -Dinstall-appdata=true
build      : |
    %ninja_build
install    : |
    %ninja_install
