name       : zoitechat
version    : 2.18.0
release    : 3
source     :
    - https://github.com/ZoiteChat/zoitechat/archive/e060d57baee1be22bee1f9c3b047be3fa71c6d35.tar.gz : ed315a0b1c46e798912fd830d3845427972857c43ccaa16284969c6f542add38
homepage   : https://zoitechat.zoite.net/
license    : GPL-2.0-only
component  : network.irc
summary    : HexChat-based IRC client
description: |
    ZoiteChat is a HexChat-based IRC client for Windows and UNIX-like systems.
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(gmodule-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ayatana-appindicator3-0.1)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(libcanberra)
    - pkgconfig(openssl)
    - pkgconfig(iso-codes)
    - meson
    - ninja
    - pkgconf
    - gcc
    - binutils
    - gettext
setup      : |
    %meson_configure \
        -Dgtk-frontend=true \
        -Dinstall-appdata=true
build      : |
    %ninja_build
install    : |
    %ninja_install
